# Generated by Django 2.2.8 on 2021-05-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObrasPorPintar',
            new_name='Obras',
        ),
    ]
