# Generated by Django 2.2.8 on 2021-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0003_auto_20210527_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='image',
            field=models.ImageField(upload_to='imagenesGafas/'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='model',
            field=models.FileField(upload_to='objects3D/'),
        ),
    ]
