# Generated by Django 2.2.8 on 2021-08-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0004_auto_20210528_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='#FFF', max_length=15)),
                ('type', models.CharField(help_text='One of ambient, directional, hemisphere, point, spot.', max_length=15)),
                ('intensity', models.FloatField(verbose_name='Intensity')),
                ('position', models.CharField(help_text='0 0 0', max_length=12)),
                ('rotation', models.CharField(help_text='0 0 0', max_length=12)),
            ],
        ),
    ]
