# Generated by Django 2.2.8 on 2021-08-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0005_lights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Scene Name')),
                ('model', models.FileField(upload_to='objects3D/scenes/')),
                ('active', models.BooleanField(default=False, verbose_name='Active Scene')),
            ],
        ),
    ]
