# Generated by Django 2.2.8 on 2021-09-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0006_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='checkpoint',
            field=models.CharField(default=1, help_text='Donde va a teletransportarse el observador ex:0 0 0', max_length=12),
            preserve_default=False,
        ),
    ]
