# Generated by Django 2.2.8 on 2021-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0008_auto_20210903_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGltf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Object')),
                ('model', models.FileField(upload_to='objects3D/object/')),
                ('active', models.BooleanField(default=False, verbose_name='Active Object')),
                ('position', models.CharField(help_text='0 0 0', max_length=150)),
                ('rotation', models.CharField(help_text='0 0 0', max_length=150)),
                ('scale', models.CharField(help_text='0 0 0', max_length=150)),
            ],
        ),
    ]
