version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'localhost -> web:8080'
      STAGE: 'local'
    volumes:
      - https-portal-data:/var/lib/https-portal
    links:
      - web
  web:
    build: ./por_pintar
    command: python manage.py runserver 0.0.0.0:8080
    container_name: web
    volumes:
      - ./por_pintar/:/usr/src/app/
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'juan_gallery'
      MYSQL_USER: 'userdb'
      MYSQL_PASSWORD: 'budablues1989'
      MYSQL_ROOT_PASSWORD: 'budablues1989'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  https-portal-data: