version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'localhost -> web:8080'
      STAGE: 'local'
    volumes:
      - https-portal-data:/var/lib/https-portal
    links:
      - web
  web:
    build: ./por_pintar
    command: python manage.py runserver 0.0.0.0:8080
    container_name: web
    volumes:
      - ./por_pintar/:/usr/src/app/
    ports:
      - 8080:8080

volumes:
  https-portal-data:

networks:
  default:
    external:
      name: juan_galeria_default