version: '3'

services:
 web:
    build: ./django_service/employees
    command: python manage.py runserver 0.0.0.0:80
    container_name: employees-web
    volumes:
      - ./django_service/employees/:/srv/src/
    ports:
      - 80:80
    restart: always

volumes:
  db-data:
    driver: local