# Generated by Django 2.2.8 on 2021-05-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObrasPorPintar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('dimentions', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date Pices')),
                ('price', models.CharField(help_text='0 0 0', max_length=150)),
                ('position', models.CharField(help_text='0 0 0', max_length=12)),
                ('rotation', models.CharField(help_text='0 0 0', max_length=12)),
                ('scale', models.CharField(help_text='0 0 0', max_length=12)),
            ],
        ),
    ]
