# Generated by Django 2.2.8 on 2021-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0002_auto_20210527_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='price',
            field=models.CharField(max_length=150),
        ),
    ]
